import Head from "next/head"
import type { GetStaticProps, NextPage } from "next"
import { client } from "libs/client"
import { Layout } from "components/FixedElement/Layout"
import { MicroCMSListResponse } from "microcms-js-sdk"
import { Anchor, Box, Space, Text, Title } from "@mantine/core"
import { Spinner } from "components/Atom/Spinner"
// import { BlogT2 } from "components/Template/BlogT2"

export type Blog = {
  title: string
  body: string
}
type Props = MicroCMSListResponse<Blog>

const Blog: NextPage<Props> = (props) => {
  // console.log(props)
  return (
    <Layout title="Blog">
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Space h="xl" />
      <div className="mx-2">
        <Title
          order={4}
          className="mt-6 mb-2 pb-4"
          sx={{
            borderBottom: "3px solid #E9ECEF",
          }}
        >
          Blog
        </Title>
        <Space h="md" />
      </div>{" "}
      <Space h="md" />
      {props.contents.map((content) => {
        return (
          <Box key={content.id} className="m-2">
            <Anchor
              className=" text-gray-700"
              href={`/blog/${content.id}`}
              weight={700}
            >
              {content.title}
            </Anchor>
            <Text size="xs">{content.body}</Text>
          </Box>
        )
      })}
      <Spinner />
      {/* <BlogT2 /> */}
    </Layout>
  )
}

export const getStaticProps: GetStaticProps<Props> = async () => {
  const data = await client.getList({ endpoint: "blog" })
  // console.log(data)

  return {
    props: data,
  }
}
export default Blog
