import Head from "next/head"
import type { NextPage } from "next"
import { Layout } from "components/FixedElement/Layout"
import { MicroCMSListResponse } from "microcms-js-sdk"
import { BlogT } from "components/Template/BlogT"

export type Blog = {
  title: string
  body: string
}
type Props = MicroCMSListResponse<Blog>

const Blog: NextPage<Props> = (props) => {
  // console.log(props)
  return (
    <Layout title="Blog">
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BlogT />
    </Layout>
  )
}
export default Blog
