import Head from 'next/head'
import type { NextPage } from 'next'
import { Layout } from 'components/FixedElement/Layout'
import { Box, Space, Text, Title } from '@mantine/core'

const Home: NextPage = () => {
  return (
    <Layout title="About">
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Space h="xl" />
        <div className="mx-2">
          <Box sx={{ borderBottom: '1px solid #E9ECEF' }}>
            <Title order={4} className="mb-3">
              About
            </Title>
          </Box>
          <Title order={5} className="my-2">
            Lightsound Shimabu
          </Title>
          <Text size="xs" className="my-2">
            ITエンジニアYouTuber。神戸大学経営学部卒。未経験から独学でプログラミングを勉強し、新卒でヤフーに入社。2019年に株式会社GameHintを創業。
          </Text>
        </div>
        <Space h="md" />
      </main>
    </Layout>
  )
}

export default Home
