import Head from 'next/head'
import type { NextPage } from 'next'
import { Layout } from 'components/FixedElement/Layout'
import { BlogT } from 'components/Template/BlogT'

const Blog: NextPage = () => {
  return (
    <Layout title="Blog">
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BlogT />
    </Layout>
  )
}

export default Blog
