import Head from 'next/head'
import type { NextPage } from 'next'
import { Layout } from 'components/FixedElement/Layout'

const Home: NextPage = () => {
  return (
    <Layout title="Contact">
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Odit soluta
        praesentium aspernatur! Nulla et sapiente enim error? Id, explicabo
        optio blanditiis corporis cupiditate fugit, quia culpa nemo labore quasi
        dolore?
      </div>
    </Layout>
  )
}

export default Home
