import Head from "next/head"
import type { NextPage } from "next"
import { Layout } from "components/FixedElement/Layout"

import { Center, Stack, Textarea, TextInput, Button } from "@mantine/core"
import { useForm } from "@mantine/form"

const Contact: NextPage = () => {
  const form = useForm({
    initialValues: {
      email: "",
      name: "",
      message: "",
    },
    validate: {
      email: (value) => (/^\S+@\S+$/.test(value) ? null : "Invalid email"),
    },
  })
  return (
    <Layout title="Contact">
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <form onSubmit={form.onSubmit((values) => console.log(values))}>
        <Stack spacing="xl">
          <TextInput
            required
            label="Email"
            placeholder="your@email.com"
            {...form.getInputProps("email")}
          />
          <TextInput
            required
            label="Name"
            placeholder="Taro Yamada"
            {...form.getInputProps("name")}
          />
          <Textarea
            required
            label="Your message"
            placeholder="I want to order your goods"
            {...form.getInputProps("message")}
          />
          <Center>
            <Button type="submit">Send Message</Button>
          </Center>
        </Stack>
      </form>
    </Layout>
  )
}

export default Contact
