import Head from "next/head"
import type { NextPage } from "next"
import { Layout } from "components/FixedElement/Layout"
import { BlogT } from "components/Template/BlogT"
import { PortFolioT } from "components/Template/PortFolioT"
import { GitHubT } from "components/Template/GitHubT"
import { TwitterT } from "components/Template/TwitterT"
import { Grid } from "@mantine/core"
import { ViewAll } from "components/Atom/ViewAll"

const Home: NextPage = () => {
  return (
    <Layout title="Home">
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BlogT />
      <ViewAll Href="/blog" />
      <PortFolioT />
      <ViewAll Href="/portfolio" />
      <Grid>
        <Grid.Col xs={12} sm={6}>
          <GitHubT />
          <ViewAll Href="/" />
        </Grid.Col>
        <Grid.Col xs={12} sm={6}>
          <TwitterT />
          <ViewAll Href="/" />
        </Grid.Col>
      </Grid>
    </Layout>
  )
}

export default Home
